version: '3'
services:
  web:
    build: .
    container_name: XAMPP_CON
    ports:
      - "8080:80"
      - "22:22"
      - "3306:3306"
    volumes:
      - .:/app
    #environment:
    #  - NAME=World
